### ISSUE TITLE
Site not functioning on internal Progress network

### ISSUE THREAD

**Issue by rdlauer** [NativeScript/plugins#54] opened 2017-01-30 14:16 UTC
The website itself comes up when accessing it on the internal network, however, none of the data gets loaded i.e. "viewing 0 of 0 plugins". This is a low priority, but if anyone has any ideas as to why this would be the case, I'd love to hear it.

**Comment by rdlauer** [comment] 2017-01-30 17:31
From Veli:

Using port 3004 for API calls in production is not advisable:

http://nativescript.rocks:3004/api/getPlugins?limit=100&offset=0&sort=marketplace_score&order=desc

It’s likely that many other organizations are filtering ports and giving users the “Viewing 0 of 0 Plugins” experience.

@NathanaelA any comments/thoughts?

**Comment by NathanaelA** [comment] 2017-01-30 18:22
This is directly related to #24 - The issue is I still need to refactor the postgresql into json files.  I'm expecting this to be done mid February.  Once I refactor the code it will all live on the same server all being server on port 80.

**Comment by NathanWalker** [comment] 2017-02-08 06:08
Fixed now in production - @rdlauer @jlooper  let us know if any further issue.

Thanks @NathanaelA 👍

**Closed by NathanWalker** 2017-02-08 06:08 UTC
Labels: in progress
